#ddev-generated
# Nextcloud add-on for DDEV
services:
  nextcloud:
    container_name: ddev-${DDEV_SITENAME}-nextcloud
    hostname: ${DDEV_SITENAME}-nextcloud
    image: nextcloud:latest
    restart: "unless-stopped"
    networks: [default, ddev_default]
    environment:
      - MYSQL_HOST=${DDEV_SITENAME}-db
      - MYSQL_DATABASE=db
      - MYSQL_USER=db
      - MYSQL_PASSWORD=db
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
      - NEXTCLOUD_TRUSTED_DOMAINS=${DDEV_SITENAME}.ddev.site
      - APACHE_DISABLE_REWRITE_IP=1
      - TRUSTED_PROXIES=172.0.0.0/8
    volumes:
      - nextcloud-data:/var/www/html
      - nextcloud-config:/var/www/html/config
      - nextcloud-apps:/var/www/html/custom_apps
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/status.php"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    depends_on:
      - db

volumes:
  nextcloud-data:
    name: "${DDEV_SITENAME}-nextcloud-data"
  nextcloud-config:
    name: "${DDEV_SITENAME}-nextcloud-config"
  nextcloud-apps:
    name: "${DDEV_SITENAME}-nextcloud-apps"
